### PR TITLE
Added Emakefile, Makefile and build.sh

### PR DESCRIPTION
**Pull request by fernandogrd**
Tested on Centos with Ejabberd 2.1.13

### CODE REVIEW

**Comment by ghosttelecom** [comment]
Brilliant! Thanks for the update!

**Comment by ghosttelecom** [comment]
????

Regards,
Shoff

**Comment by johanvorster** [comment]
get off my repo!!! :-)

**Comment by ghosttelecom** [comment]
I take it because you commented as GhostTelecom I am getting notifications now!!  So its your fault!

I am unsubscribing!

**Comment by johanvorster** [comment]
yeah, but I am not the one complaining....
Missed a good night last night!

**Pull request merged**
